#############
## validation
## will be added
#validate(config, "schema/config.schema.yaml")
#validate(samples, "schema/samples.schema.yaml")

#######################
## loading rule modules
include: "rules/extra_env.smk"         ## chekc & install all extra env
include: "rules/common.smk"            ## self-defined functions
include: "rules/cellranger_arc.smk"    ## cellranger-arc mapping, QC and joint cell calling
include: "rules/main_seurat.smk"

###################
## targeted outputs
rule all:
    input:
        get_rule_all_input()     ## for all
        ## for testing
        ##expand("cellranger-arc/{samples}_dedup.bam", samples = SAMPLES["sample_id"])   ## testing
