name: build

on:
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - devel
      - main
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        r-version: [4.0, 4.1, 4.2]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Build
        run: R CMD INSTALL .
